services:
  client:
    container_name: ${PROJECT}-client
    build:
      context: .
      dockerfile_inline: |
        FROM ubuntu:latest
        RUN apt-get update && \
            apt-get install -y \
              curl \
              openssl
    entrypoint: tail -f /dev/null
    volumes:
      - ./mtls:/opt/mtls
    working_dir: /opt/mtls
  nginx:
    image: nginx:latest
    container_name: ${PROJECT}-nginx
    expose:
      - 443
    volumes:
      - ./mtls:/opt/mtls
    working_dir: /opt/mtls
    configs:
      - source: nginx-conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - backend
  backend:
    image: kennethreitz/httpbin
    container_name: ${PROJECT}-backend
    expose:
      - 80
configs:
  nginx-conf:
    content: |
      server {
          listen 443 ssl;
          server_name nginx;

          ssl_certificate /opt/mtls/server.cert.pem;
          ssl_certificate_key /opt/mtls/server.key.pem;
          ssl_client_certificate /opt/mtls/ca-bundle.cert.pem;
          ssl_verify_client on;

          # Extract DN and forward to backend
          proxy_set_header X-Client-DN $$ssl_client_s_dn;

          location / {
              proxy_pass http://backend;
          }
      }
